window.registerTopic('Language basics & syntax', [
  { id: 'basics-1', difficulty: 'Basic', type: 'boolean',
    title: 'In Rust, variables declared with <code>let</code> are immutable by default.',
    correct: true,
    studyRef: { cheats: 'https://cheats.rs/#basic-types' } },
  { id: 'basics-2', difficulty: 'Basic', type: 'single',
    title: 'Which keyword makes a <code>let</code> binding mutable?',
    choices: ['ref', 'mut', 'move', 'dyn'],
    correct: 'mut',
    studyRef: { cheats: 'https://cheats.rs/#basic-types' } },
  { id: 'basics-3', difficulty: 'Intermediate', type: 'single',
    title: 'What is the type of a Rust function that never returns?',
    choices: ['()', 'void', '!', 'Never'],
    correct: '!',
    studyRef: { cheats: 'https://cheats.rs/#basic-types' } },
  { id: 'basics-4', difficulty: 'Intermediate', type: 'code',
    title: 'What does this code print?',
    code: 'let x = 5;\nlet x = x + 1;\n{\n    let x = x * 2;\n    println!("{x}");\n}\nprintln!("{x}");',
    choices: ['12 then 6', '12 then 12', '6 then 6', 'Compile error'],
    correct: '12 then 6',
    studyRef: { cheats: 'https://cheats.rs/#control-flow' } },
  { id: 'basics-5', difficulty: 'Intermediate', type: 'multi',
    title: 'Which of the following are valid integer literal suffixes in Rust? (select all that apply)',
    choices: ['u8', 'i64', 'usize', 'int', 'long'],
    correct: ['u8', 'i64', 'usize'],
    studyRef: { cheats: 'https://cheats.rs/#basic-types' } },
  { id: 'basics-6', difficulty: 'Intermediate', type: 'single',
    title: 'What does the <code>_</code> prefix on a variable name signal in Rust?',
    choices: [
      'The variable is private',
      'The variable is intentionally unused (suppresses unused warning)',
      'The variable is a constant',
      'The variable is mutable',
    ],
    correct: 'The variable is intentionally unused (suppresses unused warning)',
    studyRef: { cheats: 'https://cheats.rs/#basic-types' } },
  { id: 'basics-7', difficulty: 'Advanced', type: 'single',
    title: 'In Rust, <code>if</code> is an expression. What is the type of <code>if false { 1u32 } else { 2u32 }</code>?',
    choices: ['()', 'u32', 'bool', 'i32'],
    correct: 'u32',
    studyRef: { cheats: 'https://cheats.rs/#control-flow' } },
  { id: 'basics-8', difficulty: 'Advanced', type: 'code',
    title: 'What does this code print on a 64-bit platform?',
    code: "trait Speak { fn speak(&self); }\nstruct Dog;\nimpl Speak for Dog { fn speak(&self) {} }\nfn main() {\n    println!(\"{}\", std::mem::size_of::<&dyn Speak>());\n}",
    choices: ['0', '8', '16', 'Compile error'],
    correct: '16',
    studyRef: { cheats: 'https://cheats.rs/#basic-types' } },
  { id: 'basics-9', difficulty: 'Advanced', type: 'boolean',
    title: 'A non-capturing closure in Rust is a Zero-Sized Type (ZST) and can be coerced to a function pointer <code>fn()</code>.',
    correct: true,
    studyRef: { readme: '#functions' } },
  { id: 'basics-10', difficulty: 'Expert', type: 'single',
    title: 'What is the size of <code>fn(u32) -> u32</code> (a function pointer) on a 64-bit platform?',
    choices: ['0 bytes', '4 bytes', '8 bytes', '16 bytes'],
    correct: '8 bytes',
    studyRef: { readme: '#functions' } },
]);
