window.registerTopic('Async', [
  { id: 'async-1', difficulty: 'Basic', type: 'boolean',
    title: 'In Rust, an <code>async fn</code> returns a <code>Future</code> that starts executing immediately when called.',
    correct: false,
    studyRef: { cheats: 'https://cheats.rs/#async-await' } },
  { id: 'async-2', difficulty: 'Basic', type: 'single',
    title: 'What does the <code>.await</code> expression do in an async context?',
    choices: [
      'Blocks the current OS thread until the future completes',
      'Suspends the current task and yields control to the executor until the future is ready',
      'Creates a new OS thread to run the future',
      'Converts a Future into a Result',
    ],
    correct: 'Suspends the current task and yields control to the executor until the future is ready',
    studyRef: { cheats: 'https://cheats.rs/#async-await' } },
  { id: 'async-3', difficulty: 'Intermediate', type: 'single',
    title: 'An async future in Rust is compiled into:',
    choices: [
      'A closure that runs on a separate thread',
      'A state machine that implements the Future trait',
      'A callback function registered with the OS',
      'A heap-allocated coroutine object',
    ],
    correct: 'A state machine that implements the Future trait',
    studyRef: { readme: '#overhead-of-async' } },
  { id: 'async-4', difficulty: 'Intermediate', type: 'boolean',
    title: 'Tokio\'s <code>JoinSet</code> returns completed task results in the order they were spawned.',
    correct: false,
    studyRef: { readme: '#joinset-and-localset' } },
  { id: 'async-5', difficulty: 'Intermediate', type: 'single',
    title: 'What is <code>tokio::task::LocalSet</code> used for?',
    choices: [
      'Running !Send futures on the same thread without requiring Send',
      'Running futures across multiple CPU cores',
      'Creating a dedicated OS thread per async task',
      'Limiting task concurrency with a semaphore',
    ],
    correct: 'Running !Send futures on the same thread without requiring Send',
    studyRef: { readme: '#joinset-and-localset' } },
  { id: 'async-6', difficulty: 'Intermediate', type: 'multi',
    title: 'Which of the following are overhead sources specific to async Rust that do not apply to synchronous code? (select all that apply)',
    choices: [
      'State machine memory cost per await point',
      'Executor scheduling and context switching',
      'Stack allocation for every function call',
      'Complex cache access patterns from non-linear execution',
      'Heap allocation for every integer',
    ],
    correct: [
      'State machine memory cost per await point',
      'Executor scheduling and context switching',
      'Complex cache access patterns from non-linear execution',
    ],
    studyRef: { readme: '#overhead-of-async' } },
  { id: 'async-7', difficulty: 'Advanced', type: 'single',
    title: 'What trait bound must a future satisfy to be spawned on a multi-threaded Tokio runtime via <code>tokio::spawn</code>?',
    choices: [
      'Future + Clone',
      'Future + Send + \'static',
      'Future + Sync',
      'Future + Unpin',
    ],
    correct: 'Future + Send + \'static',
    studyRef: { cheats: 'https://cheats.rs/#async-await' } },
  { id: 'async-8', difficulty: 'Advanced', type: 'code',
    title: 'What does this print (assuming a Tokio runtime)?',
    code: 'async fn val() -> u32 { 42 }\n#[tokio::main]\nasync fn main() {\n    let f = val(); // future not yet polled\n    let v = f.await;\n    println!("{v}");\n}',
    choices: ['42', '0', 'Panics', 'Compile error'],
    correct: '42',
    studyRef: { cheats: 'https://cheats.rs/#async-await' } },
  { id: 'async-9', difficulty: 'Expert', type: 'boolean',
    title: 'In a latency-critical application, async Rust can add overhead compared to synchronous code due to scheduling, state machine transitions, and non-linear memory access patterns.',
    correct: true,
    studyRef: { readme: '#overhead-of-async' } },
  { id: 'async-10', difficulty: 'Expert', type: 'single',
    title: 'What does <code>tokio::select!</code> do when multiple futures are ready simultaneously?',
    choices: [
      'Awaits all of them and collects results',
      'Chooses one pseudo-randomly to avoid starvation',
      'Always picks the first branch in declaration order',
      'Panics because concurrent readiness is not allowed',
    ],
    correct: 'Chooses one pseudo-randomly to avoid starvation',
    studyRef: { cheats: 'https://cheats.rs/#async-await' } },
]);
