window.registerTopic('Tooling & Ecosystem', [
  { id: 'tool-1', difficulty: 'Basic', type: 'boolean',
    title: '<code>cargo fmt</code> formats your Rust source code according to the official Rust style guidelines.',
    correct: true,
    studyRef: { readme: '#bootstrap-environment', cheats: 'https://cheats.rs/#tooling' } },
  { id: 'tool-2', difficulty: 'Basic', type: 'single',
    title: 'Which command runs the test suite for a Rust project?',
    choices: ['cargo build', 'cargo run --test', 'cargo test', 'rustup test'],
    correct: 'cargo test',
    studyRef: { readme: '#bootstrap-environment' } },
  { id: 'tool-3', difficulty: 'Intermediate', type: 'single',
    title: 'What does <code>cargo clippy</code> do?',
    choices: [
      'Formats the source code',
      'Runs a linter that catches common mistakes and suggests idiomatic Rust improvements',
      'Audits dependencies for security vulnerabilities',
      'Generates documentation',
    ],
    correct: 'Runs a linter that catches common mistakes and suggests idiomatic Rust improvements',
    studyRef: { cheats: 'https://cheats.rs/#tooling' } },
  { id: 'tool-4', difficulty: 'Intermediate', type: 'boolean',
    title: '<code>rustup update stable</code> updates both the Rust compiler and the standard library to the latest stable release.',
    correct: true,
    studyRef: { readme: '#bootstrap-environment' } },
  { id: 'tool-5', difficulty: 'Intermediate', type: 'single',
    title: 'What does <code>cargo tree</code> show?',
    choices: [
      'The directory structure of the project',
      'The full dependency tree of the crate and its transitive dependencies',
      'The call graph of async tasks',
      'The compilation order of modules',
    ],
    correct: 'The full dependency tree of the crate and its transitive dependencies',
    studyRef: { readme: '#reduce-binary-size' } },
  { id: 'tool-6', difficulty: 'Intermediate', type: 'multi',
    title: 'Which of the following are valid profiling tools for Rust mentioned in the cheat sheet? (select all that apply)',
    choices: ['cachegrind', 'valgrind', 'dhat', 'gprof', 'perf'],
    correct: ['cachegrind', 'valgrind', 'dhat'],
    studyRef: { readme: '#profilers' } },
  { id: 'tool-7', difficulty: 'Advanced', type: 'single',
    title: 'Setting <code>CARGO_INCREMENTAL=0</code> in CI is recommended because:',
    choices: [
      'Incremental builds use more disk space and are slower in clean CI environments',
      'Incremental builds are not supported on Linux',
      'It enables full LTO',
      'It forces parallel codegen',
    ],
    correct: 'Incremental builds use more disk space and are slower in clean CI environments',
    studyRef: { readme: '#speed-up-build' } },
  { id: 'tool-8', difficulty: 'Advanced', type: 'code',
    title: 'What flag enables parallel frontend compilation in nightly Rust via <code>.cargo/config.toml</code>?',
    code: '[build]\nrustflags = ["-Z", "threads=8"]',
    choices: [
      '-Z parallel-frontend',
      '-Z threads=N',
      '--parallel',
      '-C codegen-units=8',
    ],
    correct: '-Z threads=N',
    studyRef: { readme: '#speed-up-build' } },
  { id: 'tool-9', difficulty: 'Expert', type: 'boolean',
    title: 'Using <code>lld</code> as a drop-in LLVM linker can significantly speed up the Rust link step on Linux and macOS.',
    correct: true,
    studyRef: { readme: '#speed-up-build' } },
  { id: 'tool-10', difficulty: 'Expert', type: 'single',
    title: 'What does <code>cargo llvm-lines | head -20</code> help you find?',
    choices: [
      'The 20 longest source files',
      'The functions that generate the most LLVM IR lines (expensive in terms of compile time)',
      'The 20 slowest test cases',
      'The largest binary sections',
    ],
    correct: 'The functions that generate the most LLVM IR lines (expensive in terms of compile time)',
    studyRef: { readme: '#speed-up-build' } },
]);
